-- AlterTable
ALTER TABLE "School" ADD COLUMN "selectedPlan" TEXT NOT NULL DEFAULT 'freemium';
ALTER TABLE "School" ADD COLUMN "planStatus" TEXT NOT NULL DEFAULT 'active';
ALTER TABLE "School" ADD COLUMN "planStartedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "School" ADD COLUMN "trialEndsAt" TIMESTAMP(3);
ALTER TABLE "School" ADD COLUMN "planLimits" JSONB;
